---
title: "mrna-seq-venn-diagrams"
author: "Lance Parsons"
format: html
---

## Setup

### Load libraries

```{r}
# install.packages("renv")
# renv::restore()
library(readr)
library(dplyr)
library(eulerr)
library(gridExtra)
```

### Configuration

```{r}
edits <- c("HEK3_1TtoA", "PRNP_6GtoT")
contrasts <- c(
  "PEmax.vs.PE6max.mut_editor",
  "PE6max.vs.PE6max.mut_editor",
  "PE6max.vs.PEmax_editor"
)
output_dir <- "venn-diagrams"
dir.create(output_dir, showWarnings = FALSE)
```

### Load data

```{r}
for (edit in edits) {
  for (contrast in contrasts) {
    assign(
      paste0(edit, "_", contrast, ".diffexp"),
      read_tsv(file.path(
        edit, "results", "diffexp",
        paste0(
          stringr::str_replace_all(contrast, "\\.", "-"),
          ".diffexp.symbol.tsv"
        )
      ))
    )
  }
}
```

## Venn Diagram

```{r}
for (edit in edits) {
  for (contrast in contrasts) {
    assign(
      paste0(edit, "_", contrast, ".genes"),
      get(paste0(edit, "_", contrast, ".diffexp")) %>%
        dplyr::filter(padj <= 0.05) %>%
        pull(gene)
    )
  }
}

venn.diagrams <- list()
gene.counts <- list()
for (contrast in contrasts) {
  gene.lists <- lapply(paste0(edits, "_", contrast, ".genes"), get)
  names(gene.lists) <- edits

  sink(file.path(output_dir, paste0(contrast, "_gene-lists.txt")))
  print(gene.lists)
  print(list(intersection = intersect(gene.lists[[1]], gene.lists[[2]])))
  sink()

  gene.counts[[contrast]] <- append(
    sapply(gene.lists, length),
    list("intersection" = length(intersect(gene.lists[[1]], gene.lists[[2]])))
  )
  venn.diagrams[[contrast]] <- plot(euler(gene.lists),
    quantities = TRUE,
    fill = c("#0073C2FF", "#EFC000FF"),
    main = contrast,
    xlim = 100
  )

  pdf(file.path(output_dir, paste0(contrast, "_venn-diagram.pdf")))
  plot(venn.diagrams[[contrast]])
  dev.off()

  plot(venn.diagrams[[contrast]])
}
```


```{r, fig.width=20}
venn.counts <- list()

for (contrast in contrasts) {
  venn.counts[[paste0(contrast, ":", edits[1])]] <- gene.counts[[contrast]][[edits[1]]] - gene.counts[[contrast]][["intersection"]]
  venn.counts[[paste0(contrast, ":", edits[2])]] <- gene.counts[[contrast]][[edits[2]]] - gene.counts[[contrast]][["intersection"]]
  venn.counts[[
    paste0(
      paste0(contrast, ":", edits[1]),
      "&",
      paste0(contrast, ":", edits[2])
    )
  ]] <- gene.counts[[contrast]][["intersection"]]
}

pdf(file.path(output_dir, "venn-diagrams-to-scale.pdf"), width = 14, height = 10)
venn.diagrams.scaled <-
  plot(
    euler(unlist(venn.counts)),
    quantities = TRUE,
    fill = rep(c("#0073C2FF", "#EFC000FF"), 3)
  )
venn.diagrams.scaled
dev.off()

venn.diagrams.scaled
```
