---
title: "PRNP mrna-seq-figures"
author: "Lance Parsons"
format: html
---

## Setup

### Load libraries

```{r}
# install.packages("renv")
# renv::restore()
library(DESeq2)
library(readr)
library(dplyr)
library(ggpubr)
library(ggplot2)
library(ggvenn)
```

### Configuration

```{r}
locus <- "PRNP"
results_dir <- file.path("..", "results")
contrasts <- c(
  "PEmax.vs.PE6max.mut_editor",
  "PE6max.vs.PE6max.mut_editor",
  "PE6max.vs.PEmax_editor"
)
```

### Load data

```{r}
all <- readRDS(file.path(results_dir, "deseq2", "all.rds"))
for (contrast in contrasts) {
  assign(
    paste0(contrast, ".diffexp"),
    read_tsv(file.path(
      results_dir, "diffexp",
      paste0(
        stringr::str_replace_all(contrast, "\\.", "-"),
        ".diffexp.symbol.tsv"
      )
    ))
  )
}
```

## Venn Diagram

```{r}
for (contrast in contrasts) {
  assign(
    paste0(contrast, ".genes"),
    get(paste0(contrast, ".diffexp")) %>%
      dplyr::filter(padj <= 0.05) %>%
      pull(gene)
  )
}

list.names <- contrasts %>%
  stringr::str_replace_all("\\.", " ") %>%
  stringr::str_replace_all("mut", "Mutant") %>%
  stringr::str_replace_all("_editor", "")

x <- lapply(paste0(contrasts, ".genes"), get)
names(x) <- list.names

venn.plot <- ggvenn(
  x,
  fill_color = c("#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF"),
  stroke_size = 0.5, set_name_size = 4
)

ggplot2::ggsave("venn_diagram.pdf")
venn.plot
```

### Fischer's Exact Test

```{r}
genes.to.label <- intersect(PE6max.vs.PE6max.mut_editor.genes, PE6max.vs.PEmax_editor.genes)

# Contingency table
n <- dim(PE6max.vs.PEmax_editor.diffexp)[1]
A <- PE6max.vs.PE6max.mut_editor.genes
B <- PE6max.vs.PEmax_editor.genes

ct <- matrix(
  c(
    n - length(union(A, B)),
    length(setdiff(A, B)),
    length(setdiff(B, A)),
    length(intersect(A, B))
  ),
  nrow = 2
)

ct

fisher.test(ct, alternative = "greater")
```

## MA Plots

```{r}
contrast <- "PEmax.vs.PE6max.mut_editor"

assign(
  paste0(contrast, ".maplot"),
  ggpubr::ggmaplot(
    get(paste0(contrast, ".diffexp")),
    fdr = 0.05,
    size = 0.5,
    ylim = c(-1, 1),
    fc = 1,
    genenames = get(paste0(contrast, ".diffexp"))$gene,
    top = 0,
    main = paste0(
      locus, ": ",
      contrast %>%
        stringr::str_replace_all("\\.", " ") %>%
        stringr::str_replace_all("mut", "Mutant") %>%
        stringr::str_replace_all("_editor", "")
    )
  ) +
    ggplot2::theme(legend.position = c(0.1, 0.9))
)
get(paste0(contrast, ".maplot"))

ggplot2::ggsave(paste0(contrast, ".maplot.pdf"))
```

```{r}
contrast <- "PE6max.vs.PE6max.mut_editor"

assign(
  paste0(contrast, ".maplot"),
  ggpubr::ggmaplot(
    get(paste0(contrast, ".diffexp")),
    fdr = 0.05,
    size = 0.5,
    ylim = c(-1, 1),
    fc = 1,
    genenames = get(paste0(contrast, ".diffexp"))$gene,
    top = 0,
    main = paste0(
      locus, ": ",
      contrast %>%
        stringr::str_replace_all("\\.", " ") %>%
        stringr::str_replace_all("mut", "Mutant") %>%
        stringr::str_replace_all("_editor", "")
    )
  ) +
    ggplot2::theme(legend.position = c(0.1, 0.9)) +
    ggrepel::geom_text_repel(
      data = get(paste0(contrast, ".diffexp")) %>% filter(gene %in% genes.to.label),
      aes(label = gene, x = log2(baseMean), y = log2FoldChange),
      size = 3, color = "#333333",
      min.segment.length = 0,
      max.overlaps = NA
    )
)
get(paste0(contrast, ".maplot"))

ggplot2::ggsave(paste0(contrast, ".maplot.pdf"))
```


```{r}
contrast <- "PE6max.vs.PEmax_editor"

assign(
  paste0(contrast, ".maplot"),
  ggpubr::ggmaplot(
    get(paste0(contrast, ".diffexp")),
    fdr = 0.05,
    size = 0.5,
    ylim = c(-1, 1),
    fc = 1,
    genenames = get(paste0(contrast, ".diffexp"))$gene,
    top = 0,
    main = paste0(
      locus, ": ",
      contrast %>%
        stringr::str_replace_all("\\.", " ") %>%
        stringr::str_replace_all("mut", "Mutant") %>%
        stringr::str_replace_all("_editor", "")
    )
  ) +
    ggplot2::theme(legend.position = c(0.1, 0.9)) +
    ggrepel::geom_text_repel(
      data = get(paste0(contrast, ".diffexp")) %>% filter(gene %in% genes.to.label),
      aes(label = gene, x = log2(baseMean), y = log2FoldChange),
      size = 3, color = "#333333",
      min.segment.length = 0,
      max.overlaps = NA
    )
)
get(paste0(contrast, ".maplot"))

ggplot2::ggsave(paste0(contrast, ".maplot.pdf"))
```
